// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	database "github.com/mehgokalp/insider-project/internal/domain/mysql"
	mock "github.com/stretchr/testify/mock"
)

// MessageRepository is an autogenerated mock type for the MessageRepository type
type MessageRepository struct {
	mock.Mock
}

// GetUnsentMessages provides a mock function with given fields: limit
func (_m *MessageRepository) GetUnsentMessages(limit int) ([]database.Message, error) {
	ret := _m.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for GetUnsentMessages")
	}

	var r0 []database.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]database.Message, error)); ok {
		return rf(limit)
	}
	if rf, ok := ret.Get(0).(func(int) []database.Message); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with no fields
func (_m *MessageRepository) List() ([]database.Message, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []database.Message
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]database.Message, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []database.Message); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Message)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSentStatus provides a mock function with given fields: message
func (_m *MessageRepository) UpdateSentStatus(message database.Message) error {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSentStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(database.Message) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMessageRepository creates a new instance of MessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageRepository {
	mock := &MessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
