// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	context "context"
	"github.com/mehgokalp/insider-project/internal/domain/redis"

	mock "github.com/stretchr/testify/mock"
)

// RedisMessageRepository is an autogenerated mock type for the RedisMessageRepository type
type RedisMessageRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, message
func (_m *RedisMessageRepository) Save(ctx context.Context, message redis.Message) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, redis.Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRedisMessageRepository creates a new instance of RedisMessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedisMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedisMessageRepository {
	mock := &RedisMessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
