// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	"github.com/mehgokalp/insider-project/internal/provider/webhook/dto"
	mock "github.com/stretchr/testify/mock"
)

// Requester is an autogenerated mock type for the Requester type
type Requester struct {
	mock.Mock
}

// SendSMS provides a mock function with given fields: request
func (_m *Requester) SendSMS(request dto.SendMessageRequest) (*dto.SendMessageResponse, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for SendSMS")
	}

	var r0 *dto.SendMessageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.SendMessageRequest) (*dto.SendMessageResponse, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(dto.SendMessageRequest) *dto.SendMessageResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SendMessageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.SendMessageRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRequester creates a new instance of Requester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequester(t interface {
	mock.TestingT
	Cleanup(func())
}) *Requester {
	mock := &Requester{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
